all:
  hosts:
    droplet1:
     ansible_connections: ssh
     ansible_user: root
     ansible_host: 139.59.133.75
     ansible_port: 22
    localhost:
      ansible_connection: ssh
      ansible_user: root # Remote user
      ansible_host: 139.59.133.75 # Remote host
      ansible_port: 22
